name: Build Executable

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile ºproxy_port_v_3.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: ./dist/ºproxy_port_v_3.exe
